app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/ris
#      password: 'password'
      password: 'Lilahhidb2020'
      pool-size: 30
#      username: mark
      username: gis

server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB